//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateAdminTbl
    {
        public int AccountId { get; set; }
        public string Id { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public byte[] ImageByte { get; set; }
    }
}
